name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Build and publish project
      run: |
        cd LifeBridge-MVC/LifeBridge
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ../../publish

    - name: Build Docker Image
      run: docker build -t lifebridge-app .
